use_frameworks!

platform :ios, '8.0'

target 'CQAlertView_Example' do
  pod 'CQAlertView', :path => '../'

  target 'CQAlertView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
